---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove web-image
      command: docker rmi ibrahimmintal/apache_web_app:v1.0
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t ibrahimmintal/apache_web_app:v1.0 .

    - name: Push Image to dockerhub
      command: docker push ibrahimmintal/apache_web_app:v1.0

    - name: run container
      command: docker run -d --name web-container -p 5000:80 ibrahimmintal/apache_web_app:v1.0

